package com.phasmoghostbot.telegrambot.constants;

public enum State {
    AWAITING_SELECTED,
    SELECTED_INFORMATION,
    SELECTED_INFORMATION_EVIDENCE,
    SELECTED_INFORMATION_GHOST,
    SELECTED_GHOST_SOLVER,
    SELECTED_GHOST_SOLVER_SANITY_SET,
    SELECTED_GHOST_SOLVER_SPEED_SET,
    SELECTED_GHOST_BLINK_FREQUENCY_SET,
    SELECTED_GHOST_SOLVE
}
